### PR TITLE
Sync error handling

### PR DESCRIPTION
**Pull request by jacobhilton**
Currently, request errors are common with `bbb sync` when some other process is writing to the source.

This PR makes `bbb sync` continue to sync the remaining files when it encounters such errors.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Thanks for this PR (and generally for your effort and feedback to make boostedblob better)!

copyfile raising RequestFailure is actually really rare (RequestFailures typically end up being retried until they succeed). E.g., in your situation, it's probably actually raising a FileNotFoundError.

I'm a little hesitant to just catch and postpone all exceptions here / would prefer to keep error handling simple and immediate if possible. I think I would be in favour of just ignoring FileNotFoundError... sync lists files itself and if something disappears it's clearly a racy deletion. Thoughts on https://github.com/hauntsaninja/boostedblob/pull/new/racyfiledelete ?

(And as mentioned, I think the problem you're running into should be mostly addressed in practice by https://github.com/hauntsaninja/boostedblob/commit/81617c4e130df9b62da33289556475a3fd426529 )

**Comment by hauntsaninja** [comment]
Oh I see, it is raising a RequestFailure (found a stack trace you'd posted earlier :-) ). It looks like if we're reading the middle of the file we don't convert 404s to FileNotFoundErrors.

**Comment by jacobhilton** [comment]
https://github.com/hauntsaninja/boostedblob/pull/7 looks great, thanks! Feel free to close

**Comment by hauntsaninja** [comment]
Thanks again! :-)

**Pull request closed without merging**
